spring:
  application:
    name: car-manager-backend
  webflux:
    base-path: ${APP_BASE_PATH}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  r2dbc:
    url: r2dbc:sqlserver://${DATABASE_ENDPOINT};databaseName=${DATABASE_NAME};encrypt=true;trustServerCertificate=true;
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}
  public-paths:
    - /auth/login
    - /auth/register # Ruta pública para registrar usuarios

# Logging estratégico para WebFlux y Spring Security Reactivo
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.reactive: INFO
    io.r2dbc.postgresql: INFO # Cambia a io.r2dbc.mssql si quieres ver logs del driver de SQL Server