spring:
  application:
    name: car-manager-backend
    base-path: ${APP_BASE_PATH}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  r2dbc:
    url: r2dbc:mssql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?encrypt=true&trustServerCertificate=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}
  public-paths:
    - ${APP_BASE_PATH}/auth/login

#logging:
#  level:
    # Security Logs
    #org.springframework.security: INFO
    #org.springframework.web.reactive: INFO
    # Database Logs
    #org.springframework.r2dbc: DEBUG
    #io.r2dbc.mssql: DEBUG
    #org.springframework.data.r2dbc: DEBUG